#!/bin/bash


lvdisplay


read -p "What is the name of the volume group?  " $vg
read -p "What is the name of the logical volume?        " $lv
read -p "What is the size you want to shrink to?        " $shrink_size



read -p "What is the path you would like to save the xfs dump file to?  " dump_location

df -hT

read -p "What is the /dev/mapper/ path?     " mapper
read -p "What is the mount point of the file system you want to shrink? " fs_mount_point

xfsdump -f $dump_location $fs_mount_point


umount $fs_mount_point

lvremove -f $mapper


lvcreate -L $shrink_size -n $lv $vg -y  ### force y to wipe xfs


lvdisplay

mkfs.xfs $mapper

mount $mapper $fs_mount_point

df -hT


xfsrestore -f $dump_location $fs_mount_point




echo "Make an fstab entry."
